#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/human/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi
## read ~.Xresources file ##--------------------------------------------
xrdb -merge ~/.Xresources
## set ctrl_alt_bksp as session-killer ##-------------------------------
setxkbmap -option terminate:ctrl_alt_bksp
## set startscreen ##---------------------------------------------------
if [ -e ~/.fehbg ]; then
    sh ~/.fehbg &
else
    feh --bg-fill /usr/share/backgrounds/Wall2.jpg &
fi
## applets ##-----------------------------------------------------------
sleep 5s && volumeicon &
## monitor ##-----------------------------------------------------------
sleep 5s && conky -c ~/.fluxbox/conkyrc_fluxbox &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox

# or if you want to keep a log:
# exec fluxbox -log "/home/human/.fluxbox/log"
